import childProcess from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { describe, expect, test } from "vitest";

import { defaultConfig } from "../packages/cli/src/config.ts";
import { effectiveRuntimeDigest } from "../packages/cli/src/agent-image.ts";
import { RUNFREE_VERSION } from "../packages/cli/src/embedded-assets.generated.ts";
import {
  runTsCli,
  selectCurrentDesiredControlsForTsCliProject,
  tmp,
  tmpBase,
} from "./installable-cli.test-harness.ts";

/**
 * The direct children of a top-level Compose mapping, in file order.
 *
 * The structural contract is validated against `docker compose config` by
 * `scripts/validate-runtime-compose.ts` (`make test-templates`), which needs a
 * Docker CLI. This reads the shipped template without one, so it stays a
 * two-space-indent scan rather than a parse; the template is generated by
 * `scripts/build-runtime.ts` from a fixed source, so its indentation is not a
 * variable. A reformatted template makes this throw rather than pass vacuously.
 */
function composeTopLevelKeys(compose: string, section: string): string[] {
  const lines = compose.split("\n");
  const start = lines.indexOf(`${section}:`);
  if (start === -1) throw new Error(`compose template has no top-level ${section}: mapping`);
  const keys: string[] = [];
  for (const line of lines.slice(start + 1)) {
    if (line.trim() === "" || line.startsWith("#")) continue;
    if (!line.startsWith("  ")) break;
    const key = /^ {2}([A-Za-z0-9_.-]+):/.exec(line);
    if (key) keys.push(key[1]);
  }
  if (keys.length === 0) throw new Error(`compose template ${section}: mapping parsed as empty`);
  return keys;
}

describe("installable runfree CLI: typescript runtime", () => {
  test("typescript cli initializes projects from materialized runtime templates", () => {
    const result = runTsCli(["init"]);

    expect(result.status, result.stderr).toBe(0);
    expect(fs.existsSync(path.join(tmp, ".runfree/runfree.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmp, ".runfree/network-policy.json"))).toBe(true);
    expect(fs.readFileSync(path.join(tmp, ".runfree/.gitignore"), "utf8")).toContain("state/");
    expect(fs.readFileSync(path.join(tmp, ".runfree/.gitignore"), "utf8")).toContain("config/tokens.json");
    expect(fs.readFileSync(path.join(tmp, ".runfree/.gitignore"), "utf8")).toContain("config/agent.env");
    expect(fs.existsSync(path.join(tmp, ".runfree/state/claude"))).toBe(false);
    expect(fs.existsSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/proxy/server.js"))).toBe(true);
    expect(fs.existsSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/proxy/contracts/network-policy.js"))).toBe(true);
    expect(fs.existsSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/runtime-inputs.lock.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/agent/agent-tools/package-lock.json"))).toBe(true);
    expect(fs.existsSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/proxy/package-lock.json"))).toBe(true);
    const agentDockerfile = fs.readFileSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/agent/Dockerfile"), "utf8");
    expect(agentDockerfile).toContain("ARG RUNFREE_UV_IMAGE");
    expect(agentDockerfile).not.toContain("ghcr.io/astral-sh/uv:latest");
    const compose = fs.readFileSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/agent/compose.yaml"), "utf8");
    // Post-cutover the embedded template is the per-session shape: proxy +
    // networks only, no shared agent service or its render markers. Asserted
    // as the exact service set rather than the absence of one named `agent`,
    // so a shared service reintroduced under any name fails here.
    expect(composeTopLevelKeys(compose, "services")).toEqual(["proxy"]);
    expect(compose).not.toContain("# RUNFREE_AGENT_ENV");
    expect(compose).not.toContain("# RUNFREE_AGENT_STATE_MOUNTS");
    expect(compose).not.toContain("io.runfree.container-role: agent");
    expect(compose).not.toContain("UV_SYSTEM_CERTS");
    expect(compose).not.toContain("SSL_CERT_FILE");
    expect(compose).not.toContain("REQUESTS_CA_BUNDLE");
    expect(compose).not.toContain("TERM: xterm-256color");
    expect(compose).not.toContain("COLORTERM: truecolor");
    expect(compose).not.toContain("target: ${RUNFREE_PROJECT_CONTAINER_ROOT:-/workspaces/project}");
    expect(compose).not.toContain("RUNFREE_PROJECT_COMPAT_ROOT");
    expect(compose).not.toContain("RUNFREE_PROJECT_PHYSICAL_ROOT");
    expect(compose).toContain("no-new-privileges:true");
    expect(compose).toContain("io.runfree.project-id");
    expect(compose).toContain("io.runfree.compose-project");
    expect(compose).toContain("io.runfree.digest-schema");
    expect(compose).toContain("io.runfree.proxy-image-input-digest");
    expect(compose).toContain("io.runfree.topology-digest");
    expect(compose).toContain("io.runfree.version");
    expect(compose).not.toContain("RUNFREE_PROJECTS_DIR");
    expect(compose).not.toContain("target: /workspace/projects");
    const agentToolsPackage = fs.readFileSync(path.join(tmpBase, "xdg-data/runfree/current/runtime/agent/agent-tools/package.json"), "utf8");
    expect(agentToolsPackage).toContain("@openai/codex");
    expect(agentToolsPackage).toContain("@earendil-works/pi-coding-agent");
    const config = JSON.parse(fs.readFileSync(path.join(tmp, ".runfree/runfree.json"), "utf8")) as {
      version?: number;
      agent?: unknown;
      agents?: Record<string, { command?: string } | string>;
      project?: unknown;
      paths?: unknown;
    };
    expect(config.agent).toBeUndefined();
    expect(config.version).toBe(4);
    expect(config.project).toBeUndefined();
    expect(config.paths).toBeUndefined();
    expect(config.agents?.default).toBe("claude");
    expect(config.agents?.claude).toEqual({
      command: "claude --dangerously-skip-permissions --add-dir /runfree/inbox",
    });
    expect(config.agents?.codex).toEqual({
      command: "codex -c check_for_update_on_startup=false --dangerously-bypass-approvals-and-sandbox",
    });
    expect(config.agents?.pi).toEqual({ command: "pi" });
  });

  test("typescript cli refuses runtime commands when project policy is missing", () => {
    const result = runTsCli(["status"], { RUNFREE_RUNTIME_DRY_RUN: "1" });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("missing project network policy");
    expect(result.stderr).toContain("runfree init");
    expect(fs.existsSync(path.join(tmp, ".runfree/network-policy.json"))).toBe(false);
  });

  test("typescript cli gives each runtime project a stable compose project name", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);
    selectCurrentDesiredControlsForTsCliProject();

    const result = runTsCli(["status"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(result.status, result.stderr).toBe(0);
    const dryRun = JSON.parse(result.stdout) as {
      projectRoot: string;
      composeFile: string;
      composeProjectName: string;
      env: {
        RUNFREE_CLAUDE_DIR: string;
        RUNFREE_CLAUDE_JSON: string;
        RUNFREE_CODEX_HOME: string;
        RUNFREE_PROJECT_NAME: string;
        RUNFREE_PROJECT_CONTAINER_ROOT: string;
        RUNFREE_PROJECT_COMPAT_ROOT: string;
        RUNFREE_AGENT_STATE_CLAUDE_CONFIG_DIR: string;
        RUNFREE_AGENT_STATE_CLAUDE_CONFIG_JSON: string;
        RUNFREE_AGENT_STATE_CODEX_HOME: string;
        RUNFREE_AGENT_STATE_PI_AGENT_DIR: string;
        RUNFREE_GIT_CONFIG: string;
        RUNFREE_RUNTIME_DIGEST: string;
        RUNFREE_VERSION: string;
        DOCKER_CLI_HINTS: string;
      };
      network: {
        subnet: string;
        proxyIp: string;
        agentIp: string;
      };
    };

    expect(dryRun.projectRoot).toBe(tmp);
    expect(dryRun.composeProjectName).toMatch(/^runfree-[a-f0-9]{12}$/);
    const projectHash = dryRun.composeProjectName.replace(/^runfree-/, "");
    const stateDir = path.join(tmpBase, "xdg-state/runfree/projects", projectHash);
    expect(dryRun.composeFile).toMatch(new RegExp(
      `^${stateDir.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/runtime/materializations/sha256-[a-f0-9]{64}/agent/compose\\.yaml$`,
    ));
    expect(dryRun.env.RUNFREE_CLAUDE_DIR).toBe(path.join(stateDir, "claude"));
    expect(dryRun.env.RUNFREE_CLAUDE_JSON).toBe(path.join(stateDir, "claude.json"));
    expect(dryRun.env.RUNFREE_CODEX_HOME).toBe(path.join(stateDir, "codex"));
    expect(dryRun.env.RUNFREE_PROJECT_NAME).toBe("project");
    expect(dryRun.env.RUNFREE_PROJECT_CONTAINER_ROOT).toBe("/workspaces/project");
    expect(dryRun.env.RUNFREE_PROJECT_COMPAT_ROOT).toBe("/workspace");
    expect(dryRun.env.RUNFREE_AGENT_STATE_CLAUDE_CONFIG_DIR).toBe(path.join(stateDir, "claude"));
    expect(dryRun.env.RUNFREE_AGENT_STATE_CLAUDE_CONFIG_JSON).toBe(path.join(stateDir, "claude.json"));
    expect(dryRun.env.RUNFREE_AGENT_STATE_CODEX_HOME).toBe(path.join(stateDir, "codex"));
    expect(dryRun.env.RUNFREE_AGENT_STATE_PI_AGENT_DIR).toBe(path.join(stateDir, "pi"));
    expect(dryRun.env.RUNFREE_GIT_CONFIG).toBe(path.join(stateDir, "gitconfig"));
    expect(dryRun.env.RUNFREE_RUNTIME_DIGEST).toBe(effectiveRuntimeDigest(tmp, defaultConfig()));
    expect(dryRun.env.RUNFREE_VERSION).toBe(RUNFREE_VERSION);
    expect(dryRun.env.DOCKER_CLI_HINTS).toBe("false");
    expect(dryRun.network.subnet).toMatch(/^172\.(30|31|28|29)\.\d+\.0\/24$/);
    expect(fs.existsSync(path.join(stateDir, "runtime-network.json"))).toBe(false);
    expect(fs.existsSync(path.join(tmp, ".runfree/state/runtime-network.json"))).toBe(false);
  });

  test("typed runtime commands honor dry-run before touching Docker or host git", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);
    selectCurrentDesiredControlsForTsCliProject();

    // `git` and `vnc` are typed runtime command modules (no runDefault
    // delegation). The shared dry-run front must short-circuit them the same way
    // it does the still-legacy `status` path: print the plan keyed by the
    // command name and exit 0 without running the host git capability probe or
    // any Docker call.
    const git = runTsCli(["git", "repair-worktree-links"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(git.status, git.stderr).toBe(0);
    expect((JSON.parse(git.stdout) as { command: string }).command).toBe("git");

    const vnc = runTsCli(["vnc", "start", "--no-password"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(vnc.status, vnc.stderr).toBe(0);
    expect((JSON.parse(vnc.stdout) as { command: string }).command).toBe("vnc");

    const up = runTsCli(["up", "--audit-network=2h"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(up.status, up.stderr).toBe(0);
    expect((JSON.parse(up.stdout) as { command: string }).command).toBe("up");

    const audit = runTsCli(["audit", "status"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(audit.status, audit.stderr).toBe(0);
    expect((JSON.parse(audit.stdout) as { command: string }).command).toBe("audit");

    // Bare `deps` defaults to plan; the dry-run front short-circuits it keyed
    // "deps" before any overlay/Docker work.
    const deps = runTsCli(["deps"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(deps.status, deps.stderr).toBe(0);
    expect((JSON.parse(deps.stdout) as { command: string }).command).toBe("deps");

    // The simple read-only/teardown/session commands are typed modules too; each
    // honors the dry-run front before any Docker call.
    for (const name of ["resources", "sessions", "stop", "destroy", "shell"] as const) {
      const r = runTsCli([name], { RUNFREE_RUNTIME_DRY_RUN: "1" });
      expect(r.status, `${name}: ${r.stderr}`).toBe(0);
      expect((JSON.parse(r.stdout) as { command: string }).command).toBe(name);
    }

    // The typed `$0 [agent]` default honors dry-run keyed by the agent name, or
    // "default" for a bare invocation.
    const bare = runTsCli([], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(bare.status, bare.stderr).toBe(0);
    expect((JSON.parse(bare.stdout) as { command: string }).command).toBe("default");

    const agent = runTsCli(["claude"], { RUNFREE_RUNTIME_DRY_RUN: "1" });
    expect(agent.status, agent.stderr).toBe(0);
    expect((JSON.parse(agent.stdout) as { command: string }).command).toBe("claude");
  }, 60_000);

  test("dependency overlay scans do not run a repository fsmonitor hook", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);
    selectCurrentDesiredControlsForTsCliProject();

    const gitInit = childProcess.spawnSync("git", ["-C", tmp, "init", "--quiet"], { encoding: "utf8" });
    expect(gitInit.status, gitInit.stderr).toBe(0);

    const marker = path.join(tmp, ".git", "fsmonitor-ran");
    const legacyBooleanMarker = path.join(tmp, ".git", "fsmonitor-false-ran");
    const hook = path.join(tmp, "fsmonitor-hook.sh");
    fs.writeFileSync(hook, [
      "#!/bin/sh",
      "printf ran > .git/fsmonitor-ran",
      "printf '0\\0'",
      "",
    ].join("\n"), { mode: 0o755 });
    fs.writeFileSync(path.join(tmp, "false"), [
      "#!/bin/sh",
      "printf ran > .git/fsmonitor-false-ran",
      "printf '0\\0'",
      "",
    ].join("\n"), { mode: 0o755 });
    const gitConfig = childProcess.spawnSync(
      "git",
      ["-C", tmp, "config", "core.fsmonitor", "./fsmonitor-hook.sh"],
      { encoding: "utf8" },
    );
    expect(gitConfig.status, gitConfig.stderr).toBe(0);

    const result = runTsCli(["up"], {
      PATH: `${tmp}${path.delimiter}${process.env.PATH ?? ""}`,
      RUNFREE_RUNTIME_DRY_RUN: "1",
    });

    expect(result.status, result.stderr).toBe(0);
    expect(fs.existsSync(marker)).toBe(false);
    expect(fs.existsSync(legacyBooleanMarker)).toBe(false);
  });

  test("typescript cli prints dependency overlay plans without starting Docker", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);
    fs.writeFileSync(path.join(tmp, "package.json"), JSON.stringify({ packageManager: "pnpm@10.28.0" }));
    fs.writeFileSync(path.join(tmp, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");

    const result = runTsCli(["deps", "plan"], { RUNFREE_TEST_FAKE_DOCKER: "1" });

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain("dependency overlays");
    expect(result.stdout).toContain("package managers: pnpm");
    expect(result.stdout).toContain("/workspace/node_modules");
    expect(result.stdout).toContain("pnpm install --frozen-lockfile");
    expect(result.stderr).toBe("");
  });

  test("typescript cli reports dependency overlay input errors without stacks", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);
    fs.writeFileSync(path.join(tmp, "package.json"), `${JSON.stringify({ packageManager: "pnpm@10.28.0" })}\n`);
    fs.writeFileSync(path.join(tmp, "pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    fs.writeFileSync(path.join(tmp, "pnpm-workspace.yaml"), "packages: &workspace_packages\n  - packages/*\n");

    const result = runTsCli(["deps", "plan"], { RUNFREE_TEST_FAKE_DOCKER: "1" });

    expect(result.status).toBe(1);
    expect(result.stderr).toContain("runfree error: dependency overlay plan failed: unsupported pnpm-workspace.yaml packages syntax");
    expect(result.stderr).not.toContain("at createDependencyOverlayPlan");
  });

  test("typescript cli imports a clipboard image into host state and prints the container path", () => {
    const source = path.join(tmpBase, "clip.png");
    fs.writeFileSync(source, Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3]));

    const result = runTsCli(["inbox", "paste"], {
      RUNFREE_TEST_CLIPBOARD_IMAGE_PATH: source,
      RUNFREE_TEST_INBOX_RANDOM: "a8f3",
    });

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout.trim()).toMatch(/^\/runfree\/inbox\/clip-\d{4}-\d{2}-\d{2}-\d{6}-a8f3\.png$/);
    const stateRoot = path.join(tmpBase, "xdg-state", "runfree", "projects");
    const files = fs.readdirSync(stateRoot, { recursive: true }).map(String);
    expect(files.some((entry) => /inbox\/clip-.*-a8f3\.png$/.test(entry))).toBe(true);
    expect(fs.existsSync(path.join(tmp, ".runfree"))).toBe(false);
  });

  test("typescript cli still prints the imported image path when clipboard copy fails", () => {
    const source = path.join(tmpBase, "clip.png");
    fs.writeFileSync(source, Buffer.from([0x89, 0x50, 0x4e, 0x47, 1, 2, 3]));

    const result = runTsCli(["inbox", "paste", "--copy"], {
      RUNFREE_TEST_CLIPBOARD_COPY_ERROR: "forced copy failure",
      RUNFREE_TEST_CLIPBOARD_IMAGE_PATH: source,
      RUNFREE_TEST_INBOX_RANDOM: "a8f4",
    });

    expect(result.status).toBe(0);
    expect(result.stdout.trim()).toMatch(/^\/runfree\/inbox\/clip-\d{4}-\d{2}-\d{2}-\d{6}-a8f4\.png$/);
    expect(result.stderr).toContain("warning: image imported at /runfree/inbox/");
    expect(result.stderr).toContain("copy failed:");
  });

  test("typescript cli runs admin commands in-process against the project policy", () => {
    const init = runTsCli(["init"]);
    expect(init.status, init.stderr).toBe(0);

    const fakeBin = path.join(tmp, "fake-bin");
    fs.mkdirSync(fakeBin);
    fs.writeFileSync(path.join(fakeBin, "docker"), "#!/bin/sh\nexit 0\n");
    fs.chmodSync(path.join(fakeBin, "docker"), 0o755);

    const result = runTsCli([
      "host",
      "add",
      "example.org",
      "--no-reload",
    ], { PATH: `${fakeBin}:${process.env.PATH ?? ""}` });

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain("example.org updated");
    expect(result.stdout).toContain("effective policy: unchanged (--no-reload)");
    expect(fs.readFileSync(path.join(tmp, ".runfree/network-policy.json"), "utf8")).toContain("example.org");
  });

});
